apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-nodes-backend
  namespace: backoffice-nodes
  labels:
    app-code: ms-nodes-backend
    app-role: domain
    app-group: backend
    app-plattform: backoffice-nodes
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app-code: ms-nodes-backend
  strategy:
    rollingUpdate:
      maxSurge: 25% #porcentajee de pod nuevos en el despliegue (new version)
      maxUnavailable: 25% #porcentanje de pod que elimina en el despliegue (old version)
    type: RollingUpdate
  template:
    metadata:
      labels:
        app-code: ms-nodes-backend
    spec:
      containers:
        - name: ms-nodes-backend
          image: gcr.io/lacchain-bid/ms-nodes-backend:1.0.18
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SEVER_PORT
              value: "5000"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-user-pass
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-user-pass
                  key: password
            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: mail-user-pass
                  key: username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-user-pass
                  key: password
            - name: DB_HOST
              value: ms-mongo-service-svc
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: lacnetdb
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          # livenessProbe:
          #   httpsGet:
          #     path: /health
          #     port: 5000
          #   initialDelaySeconds: 10
          #   periodSeconds: 180
          #   timeoutSeconds: 3
          #   failureThreshold: 3
          # readinessProbe:
          #   httpsGet:
          #     path: /health
          #     port: 5000
          #   initialDelaySeconds: 25
          #   timeoutSeconds: 3
          #   failureThreshold: 3

---
kind: Service
apiVersion: v1
metadata:
  name: ms-nodes-backend-svc
  namespace: backoffice-nodes
  labels:
    svc-code: ms-nodes-backend-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 34.71.112.114 
  selector:
    app-code: ms-nodes-backend
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5000
      name: http



